### ISSUE TITLE
Why package is DISCONTINUED ?

### ISSUE THREAD

**Issue by Hellomik2002** [am15h/tflite_flutter_helper#71]

**Comment by mirland** [comment]
@PaulTR Can you please explain the future of this plugin? I mean, what are the plans for it? are you planning to merge it with the main plugin? Or are you planning just to deprecate it? 

I think this plugin it's important to process images, so these methods should be present in somewhere

**Comment by PaulTR** [comment]
This one is discontinued because we don't plan to update it past where it is right now. That said, we're working on a Flutter plugin to replace it based on a new project we're working on called [MediaPipe Tasks](https://github.com/googlesamples/mediapipe). It's not ready for the main stage yet, but it'll definitely cover the core features here without a lot of the older overhead. Until then though this will still exist with the same update frequency (e.g. none :P), but we're definitely working on getting the plugin out as soon as possible. I've already selected two students for the [Google Summer of Code](https://docs.google.com/document/d/1w7MoOy7FJwECdl3gifPttLN-HnRyWG1kJkTg2g8uKz4/edit?usp=sharing) to help flesh it out on GitHub after we have the base of it in, as well.

**Comment by Hellomik2002** [comment]
Can we help?

**Comment by PaulTR** [comment]
@Hellomik2002 Not yet, but soon! I'm going through the good ol' Google bureaucracy to get the foundation in, then it'll be open for community contribution :)

**Comment by Hellomik2002** [comment]
Thank you very much for your attention, this package helped me get rid of a lot of build problems with Cmake and one other C++ issues.
